name: Build vLLM EP Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/vllm-ep
      IMAGE_TAG: latest
      TORCH_VERSION: 2.4.1
      VLLM_VERSION: 0.10.0
      NVSHMEM_VER: 2.10.0-1
      CUDA_VERSION: 12.3.2
      PYTHON_VERSION: 3.10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU (for cross-platform builds, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg TORCH_VERSION=${{ env.TORCH_VERSION }} \
            --build-arg VLLM_VERSION=${{ env.VLLM_VERSION }} \
            --build-arg NVSHMEM_VER=${{ env.NVSHMEM_VER }} \
            --build-arg PYTHON_VERSION=${{ env.PYTHON_VERSION }} \
            -t $IMAGE_NAME:$IMAGE_TAG \
            .

      - name: Test Docker Image (sanity check)
        run: |
          docker run --rm $IMAGE_NAME:$IMAGE_TAG python3 -c "import torch; import vllm; print('vLLM EP image ok')"

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
